/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "conf.h"
#include "hal.h"
#include "gpio_hal.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

const gpio_hal_cfg_t*  gpio_prova_conf;

int main(void)
{
    gpio_prova_conf = Gpio_hal_conf_get();
	// prepare the eventual additiona HAL layers
	Core_hal_init();
	// clock


	Gpio_hal_init(gpio_prova_conf);
	Gpio_hal_write_value(DEBUG_LED, GPIO_HAL_VAL_TRUE);
	Gpio_hal_write_value(DEBUG_LED, GPIO_HAL_VAL_FALSE);

	for(;;)
	{
	    Gpio_hal_write_value(DEBUG_LED, GPIO_HAL_VAL_TRUE);
	    Gpio_hal_write_value(DEBUG_LED, GPIO_HAL_VAL_FALSE);
	}
}
