/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "conf.h"
#include "os.h"
#include "hal.h"
#include "gpio_hal.h"

#warning "USE_FREERTOS not defined, ISR will not work with this"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define mainQUEUE_RECEIVE_PARAMETER ( 0x22UL )
#define mainQUEUE_SEND_PARAMETER ( 0x1111UL )

const gpio_hal_cfg_t*  gpio_prova_conf;
/* The queue used by both tasks. */
static QueueHandle_t xQueue = NULL;

static void prvQueueSendTask( void *pvParameters )
{
TickType_t xNextWakeTime;
const unsigned long ulValueToSend = 100UL;

    /* Check the task parameter is as expected. */
    configASSERT( ( ( unsigned long ) pvParameters ) == mainQUEUE_SEND_PARAMETER );

    /* Initialise xNextWakeTime - this only needs to be done once. */
    xNextWakeTime = xTaskGetTickCount();

    for( ;; )
    {
        /* Place this task in the blocked state until it is time to run again.
        The block time is specified in ticks, the constant used converts ticks
        to ms.  While in the Blocked state this task will not consume any CPU
        time. */
        vTaskDelayUntil( &xNextWakeTime, ( pdMS_TO_TICKS( 1000UL ) ) );

        /* Send to the queue - causing the queue receive task to unblock and
        toggle the LED.  0 is used as the block time so the sending operation
        will not block - it shouldn't need to block as the queue should always
        be empty at this point in the code. */
        xQueueSend( xQueue, &ulValueToSend, 0U );
    }
}
/*-----------------------------------------------------------*/

static void prvQueueReceiveTask( void *pvParameters )
{
unsigned long ulReceivedValue;
static const TickType_t xShortBlock = pdMS_TO_TICKS( 50 );

    /* Check the task parameter is as expected. */
    configASSERT( ( ( unsigned long ) pvParameters ) == mainQUEUE_RECEIVE_PARAMETER );

    for( ;; )
    {
        /* Wait until something arrives in the queue - this task will block
        indefinitely provided INCLUDE_vTaskSuspend is set to 1 in
        FreeRTOSConfig.h. */
        xQueueReceive( xQueue, &ulReceivedValue, portMAX_DELAY );

        /*  To get here something must have been received from the queue, but
        is it the expected value?  If it is, toggle the LED. */
        if( ulReceivedValue == 100UL )
        {
            /* Blip the LED for a short while so as not to use too much
            power. */
           // vMainToggleLED();
            Gpio_hal_write_value(DEBUG_LED, GPIO_HAL_VAL_TRUE);
            vTaskDelay( xShortBlock );
            Gpio_hal_write_value(DEBUG_LED, GPIO_HAL_VAL_FALSE);
           // vMainToggleLED();
            ulReceivedValue = 0U;
        }
    }
}

int main(void)
{
    gpio_prova_conf = Gpio_hal_conf_get();
	// prepare the eventual additiona HAL layers
	Core_hal_init();
	// clock


	Gpio_hal_init(gpio_prova_conf);
	Gpio_hal_write_value(DEBUG_LED, GPIO_HAL_VAL_TRUE);
	Gpio_hal_write_value(DEBUG_LED, GPIO_HAL_VAL_FALSE);


	/* Create the queue. */
    xQueue = xQueueCreate( 1, sizeof( uint32_t ) );

    if( xQueue != NULL )
    {
        /* Start the two tasks as described in the comments at the top of this
        file. */
        xTaskCreate( prvQueueReceiveTask,                   /* The function that implements the task. */
                    "Rx",                                   /* The text name assigned to the task - for debug only as it is not used by the kernel. */
                    configMINIMAL_STACK_SIZE,               /* The size of the stack to allocate to the task. */
                    ( void * ) mainQUEUE_RECEIVE_PARAMETER, /* The parameter passed to the task - just to check the functionality. */
                    ( tskIDLE_PRIORITY + 2 ),        /* The priority assigned to the task. */
                    NULL );                                 /* The task handle is not required, so NULL is passed. */

        xTaskCreate( prvQueueSendTask, "TX", configMINIMAL_STACK_SIZE, ( void * ) mainQUEUE_SEND_PARAMETER, ( tskIDLE_PRIORITY + 1 ), NULL );

        /* Start the tasks and timer running. */
        vTaskStartScheduler();
    }

	for(;;)
	{
	  //  Gpio_hal_write_value(DEBUG_LED, GPIO_HAL_VAL_TRUE);
	  //  Gpio_hal_write_value(DEBUG_LED, GPIO_HAL_VAL_FALSE);
	}
}


void vApplicationStackOverflowHook( TaskHandle_t pxTask, char *pcTaskName )
{
    ( void ) pcTaskName;
    ( void ) pxTask;

    /* Run time stack overflow checking is performed if
    configCHECK_FOR_STACK_OVERFLOW is defined to 1 or 2.  This hook
    function is called if a stack overflow is detected. */

    /* Force an assert. */
    configASSERT( ( volatile void * ) NULL );
}

void vMainAssertCalled( const char *pcFileName, uint32_t ulLineNumber )
{
    //xil_printf( "ASSERT!  Line %lu of file %s\r\n", ulLineNumber, pcFileName );
    taskENTER_CRITICAL();
    for( ;; );
}
