/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "conf.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	Core_hal_init();
	Timer_hal_init(timer_hal_conf);
	Gpio_hal_init(gpio_hal_conf, CONF_TOTAL_APP_PIN);
	Gpio_hal_set_value(DEBUG_LED, GPIO_HIGH);
	Gpio_hal_set_value(DEBUG_LED, GPIO_LOW);
	//tmr start

	for(;;);
}
